SERIAL = "SLUS_206.22"
MFA_ARCHIVE = "B0.MFA"

ASM = "asm"
BUILD = "build"
CONFIG = "config"
INCLUDE = "include"
LINKERS = "linkers"
ROM = "rom"
SRC = "src"
TOOLS = "tools"
ADDR2LINE_PATH = f"{TOOLS}/binutils-mips-ps2-decompals/mips-ps2-decompals-addr2line"
