name: alessa

on:
  push:
    branches:
      - main
      - ci/test
    paths-ignore:
      - '**.md'

jobs:
  build:
    if: github.repository == 'dreamingmoths/memory-of-alessa'
    container:
      image: ghcr.io/dreamingmoths/alessa:latest
      credentials:
        username: dreamingmoths
        password: ${{ secrets.GHCR_TOKEN }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        TARGET:
          - {
              GAME: "Silent Hill 3",
              SERIAL: "SLUS_206.22",
              ALIAS: "sh3"
            }
          - {
              GAME: "Silent Hill 2",
              SERIAL: "SLUS_202.28",
              ALIAS: "sh2"
            }

    permissions:
      contents: read
      packages: read

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          lfs: true

      - name: install python dependencies
        run: python3 -m pip install --break-system-packages -r requirements.txt

      - name: copy files
        run: cp -r /home/* .

      - name: build matching executable
        run: make -j $(nproc) ${{ matrix.TARGET.ALIAS }}
      
      - name: clean build files
        run: make ${{ matrix.TARGET.ALIAS }}-clean

      - name: make report
        run: make -j $(nproc) ${{ matrix.TARGET.ALIAS }}-report

      - name: upload to silenthillmuseum.org
        env:
          SERIAL: ${{ matrix.TARGET.SERIAL }}
          PROGRESS_API_KEY: ${{ secrets.PROGRESS_API_KEY }}
        run: tools/scripts/upload-progress.sh

      - name: release artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.TARGET.SERIAL }}_report
          path: build/${{ matrix.TARGET.SERIAL }}/report.json
